package abarrotesrios_magm.vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Color;

public class Principal extends javax.swing.JFrame {

    ImageIcon imagen;
    Icon icono;
    Portada portada = new Portada();
    
    
    
    public Principal() {
        initComponents();

        this.setSize(1169, 780);
        this.setLocationRelativeTo(null);
        
        panel(portada);
        cambioImagen("fondoBotones.jpg", lblBotonesBackround);
        this.setLocationRelativeTo(null);
        
        
    }
    
    public void cambioImagen(String nombreImagen, JLabel etiqueta){
        imagen = new ImageIcon("src/imgs/" + nombreImagen);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiqueta.getWidth(), etiqueta.getHeight(), Image.SCALE_DEFAULT));
        etiqueta.setIcon(icono);
        
    }
    
    public void panel (JPanel formulario){
        pnlContenedor.removeAll();
        pnlContenedor.setLayout(new BorderLayout()); 
        pnlContenedor.add(formulario, BorderLayout.CENTER);

        pnlContenedor.revalidate();
        pnlContenedor.repaint();
        formulario.setSize(pnlContenedor.getWidth(), pnlContenedor.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpBotones = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblBotonesBackround = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jpBotones.setBackground(new java.awt.Color(255, 255, 204));
        jpBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpBotones.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(100, 10, 140, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/x-mark-4-48.png"))); // NOI18N
        jButton2.setText("SALIR");
        jButton2.setIconTextGap(20);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/x-mark-4-55.png"))); // NOI18N
        jPanel4.add(jButton2);
        jButton2.setBounds(0, 450, 250, 80);

        btnClientes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/clients-48.png"))); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.setIconTextGap(20);
        btnClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/conference-55.png"))); // NOI18N
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel4.add(btnClientes);
        btnClientes.setBounds(0, 50, 250, 80);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/truck-2-48.png"))); // NOI18N
        jButton4.setText("PROVEEDORES");
        jButton4.setIconTextGap(20);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/truck-2-55.png"))); // NOI18N
        jPanel4.add(jButton4);
        jButton4.setBounds(0, 130, 250, 80);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bunch-ingredients-48.png"))); // NOI18N
        jButton5.setText("PRODUCTOS");
        jButton5.setIconTextGap(20);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bunch-ingredients-55.png"))); // NOI18N
        jPanel4.add(jButton5);
        jButton5.setBounds(0, 210, 250, 80);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/text-file-3-48.png"))); // NOI18N
        jButton6.setText("VENTAS");
        jButton6.setIconTextGap(20);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/text-file-3-55.png"))); // NOI18N
        jPanel4.add(jButton6);
        jButton6.setBounds(0, 290, 250, 80);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/combo-48.png"))); // NOI18N
        jButton7.setText("REPORTES");
        jButton7.setIconTextGap(20);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/combo-55.png"))); // NOI18N
        jPanel4.add(jButton7);
        jButton7.setBounds(0, 370, 250, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 30);

        jpBotones.add(jPanel4);
        jPanel4.setBounds(20, 70, 250, 530);
        jpBotones.add(lblBotonesBackround);
        lblBotonesBackround.setBounds(0, 0, 290, 660);

        jPanel1.add(jpBotones);
        jpBotones.setBounds(30, 40, 290, 660);

        pnlContenedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlContenedor.setLayout(null);
        jPanel1.add(pnlContenedor);
        pnlContenedor.setBounds(340, 40, 800, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        ClientesPanel clientes = new ClientesPanel();
        panel(clientes);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        // TODO add your handling code here:
        btnClientes.setBackground(Color.red);
        
    }//GEN-LAST:event_btnClientesMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JLabel lblBotonesBackround;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
