package abarrotesrios_magm.vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Color;

public class Principal extends javax.swing.JFrame {

    ImageIcon imagen;
    Icon icono;
    Portada portada = new Portada();
    
    
    
    public Principal() {
        initComponents();

        this.setSize(1169, 780);
        this.setLocationRelativeTo(null);
        
        panel(portada);
        cambioImagen("fondoBotones.jpg", lblBotonesBackround);
        this.setLocationRelativeTo(null);
        
        
    }
    
    public void cambioImagen(String nombreImagen, JLabel etiqueta){
        imagen = new ImageIcon("src/imgs/" + nombreImagen);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiqueta.getWidth(), etiqueta.getHeight(), Image.SCALE_DEFAULT));
        etiqueta.setIcon(icono);
        
    }
    
    public void panel (JPanel formulario){
        pnlContenedor.removeAll();
        pnlContenedor.setLayout(new BorderLayout()); 
        pnlContenedor.add(formulario, BorderLayout.CENTER);

        pnlContenedor.revalidate();
        pnlContenedor.repaint();
        formulario.setSize(pnlContenedor.getWidth(), pnlContenedor.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpBotones = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblBotonesBackround = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jpBotones.setBackground(new java.awt.Color(255, 255, 204));
        jpBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpBotones.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(100, 10, 140, 30);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/x-mark-4-48.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setIconTextGap(20);
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/x-mark-4-55.png"))); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanel4.add(btnSalir);
        btnSalir.setBounds(0, 450, 250, 80);

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/clients-48.png"))); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.setIconTextGap(20);
        btnClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/conference-55.png"))); // NOI18N
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel4.add(btnClientes);
        btnClientes.setBounds(0, 50, 250, 80);

        btnProveedor.setBackground(new java.awt.Color(255, 255, 255));
        btnProveedor.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/truck-2-48.png"))); // NOI18N
        btnProveedor.setText("PROVEEDORES");
        btnProveedor.setIconTextGap(20);
        btnProveedor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/truck-2-55.png"))); // NOI18N
        btnProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProveedorMouseExited(evt);
            }
        });
        jPanel4.add(btnProveedor);
        btnProveedor.setBounds(0, 130, 250, 80);

        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bunch-ingredients-48.png"))); // NOI18N
        btnProductos.setText("PRODUCTOS");
        btnProductos.setIconTextGap(20);
        btnProductos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bunch-ingredients-55.png"))); // NOI18N
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductosMouseExited(evt);
            }
        });
        jPanel4.add(btnProductos);
        btnProductos.setBounds(0, 210, 250, 80);

        btnVentas.setBackground(new java.awt.Color(255, 255, 255));
        btnVentas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/text-file-3-48.png"))); // NOI18N
        btnVentas.setText("VENTAS");
        btnVentas.setIconTextGap(20);
        btnVentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/text-file-3-55.png"))); // NOI18N
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentasMouseExited(evt);
            }
        });
        jPanel4.add(btnVentas);
        btnVentas.setBounds(0, 290, 250, 80);

        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/combo-48.png"))); // NOI18N
        btnReportes.setText("REPORTES");
        btnReportes.setIconTextGap(20);
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/combo-55.png"))); // NOI18N
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
        });
        jPanel4.add(btnReportes);
        btnReportes.setBounds(0, 370, 250, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 30);

        jpBotones.add(jPanel4);
        jPanel4.setBounds(20, 70, 250, 530);
        jpBotones.add(lblBotonesBackround);
        lblBotonesBackround.setBounds(0, 0, 290, 660);

        jPanel1.add(jpBotones);
        jpBotones.setBounds(30, 40, 290, 660);

        pnlContenedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlContenedor.setLayout(null);
        jPanel1.add(pnlContenedor);
        pnlContenedor.setBounds(340, 40, 800, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        ClientesPanel clientes = new ClientesPanel();
        panel(clientes);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        // TODO add your handling code here:
       btnClientes.setBackground(Color.decode("#756766"));
        
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        // TODO add your handling code here:
        btnClientes.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedorMouseEntered
        // TODO add your handling code here:
        btnProveedor.setBackground(Color.decode("#756766"));
    }//GEN-LAST:event_btnProveedorMouseEntered

    private void btnProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseEntered
        // TODO add your handling code here:
        btnProductos.setBackground(Color.decode("#756766"));
    }//GEN-LAST:event_btnProductosMouseEntered

    private void btnVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseEntered
        // TODO add your handling code here:
        btnVentas.setBackground(Color.decode("#756766"));
    }//GEN-LAST:event_btnVentasMouseEntered

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        // TODO add your handling code here:
        btnReportes.setBackground(Color.decode("#756766"));
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        btnSalir.setBackground(Color.decode("#756766"));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedorMouseExited
        // TODO add your handling code here:
        btnProveedor.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnProveedorMouseExited

    private void btnProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseExited
        // TODO add your handling code here:
        btnProductos.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnProductosMouseExited

    private void btnVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseExited
        // TODO add your handling code here:
        btnVentas.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnVentasMouseExited

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        // TODO add your handling code here:
        btnReportes.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnReportesMouseExited

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        btnSalir.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnProductos;
    public javax.swing.JButton btnProveedor;
    public javax.swing.JButton btnReportes;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JLabel lblBotonesBackround;
    public javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
