/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abarrotesrios_magm.vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author MICHAEL GUERRA
 */
public class ProductosPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClientesPanel
     */
    
    ImageIcon imagen;
    Icon icono;
    public ProductosPanel() {
        initComponents();
        cambioImagen("logoAbarrotes.png", lblLogo);
        
//        
    }
    
        
    public void cambioImagen(String nombreImagen, JLabel etiqueta) {
        imagen = new ImageIcon("src/imgs/" + nombreImagen);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiqueta.getWidth(), etiqueta.getHeight(), Image.SCALE_DEFAULT));
        etiqueta.setIcon(icono);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfPrecio = new javax.swing.JTextField();
        jtfStockMax = new javax.swing.JTextField();
        botBuscarCodigo = new javax.swing.JButton();
        botBuscarDescripcion = new javax.swing.JButton();
        jtfDescripcion = new javax.swing.JTextField();
        jcbProveedor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jtfCosto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfStockMin = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        botCrear = new javax.swing.JButton();
        botLeer = new javax.swing.JButton();
        botMdificar = new javax.swing.JButton();
        botEliminar = new javax.swing.JButton();
        botLimpiar = new javax.swing.JButton();
        botSalir = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 340, 780, 10);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 150, 780, 10);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3), "PROVEEDORES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "CIUDAD", "TELEFONO"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(10, 360, 780, 290);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3), "DATOS DEL PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CODIGO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(7, 35, 59, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DESCRIPCION");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 35, 103, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("COSTO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 80, 50, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("STOCK MAX");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(570, 80, 100, 17);

        jtfCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtfCodigo);
        jtfCodigo.setBounds(70, 32, 70, 23);

        jtfPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtfPrecio);
        jtfPrecio.setBounds(250, 80, 90, 23);

        jtfStockMax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtfStockMax);
        jtfStockMax.setBounds(670, 80, 90, 23);

        botBuscarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/search-9-16.png"))); // NOI18N
        jPanel1.add(botBuscarCodigo);
        botBuscarCodigo.setBounds(147, 32, 46, 23);

        botBuscarDescripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/search-9-16.png"))); // NOI18N
        jPanel1.add(botBuscarDescripcion);
        botBuscarDescripcion.setBounds(448, 32, 46, 23);

        jtfDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtfDescripcion);
        jtfDescripcion.setBounds(308, 32, 128, 23);

        jcbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jcbProveedor);
        jcbProveedor.setBounds(610, 32, 151, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("PROVEEDOR");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(509, 34, 89, 17);

        jtfCosto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtfCosto);
        jtfCosto.setBounds(70, 80, 90, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PRECIO");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(180, 80, 56, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("STOCK MIN");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 80, 100, 17);

        jtfStockMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtfStockMin);
        jtfStockMin.setBounds(460, 80, 90, 23);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botCrear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        botCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/add-user-3-24.png"))); // NOI18N
        botCrear.setText("CREAR");
        botCrear.setToolTipText("");

        botLeer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        botLeer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-buscar-contactos-24.png"))); // NOI18N
        botLeer.setText("LEER");
        botLeer.setToolTipText("");
        botLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLeerActionPerformed(evt);
            }
        });

        botMdificar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        botMdificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/available-updates-24.png"))); // NOI18N
        botMdificar.setText("MODIFICA");
        botMdificar.setToolTipText("");

        botEliminar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        botEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/delete-24.png"))); // NOI18N
        botEliminar.setText("ELIMINAR");
        botEliminar.setToolTipText("");

        botLimpiar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        botLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-borrar-24.png"))); // NOI18N
        botLimpiar.setText("LIMPIAR");
        botLimpiar.setToolTipText("");

        botSalir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        botSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/x-mark-24.png"))); // NOI18N
        botSalir.setText("SALIR");
        botSalir.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(botCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(botLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(botMdificar)
                .addGap(0, 0, 0)
                .addComponent(botEliminar)
                .addGap(0, 0, 0)
                .addComponent(botLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(botSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botCrear)
                .addComponent(botMdificar)
                .addComponent(botLeer)
                .addComponent(botEliminar)
                .addComponent(botSalir)
                .addComponent(botLimpiar))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 120, 750, 37);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(10, 160, 780, 170);
        jPanel3.add(lblLogo);
        lblLogo.setBounds(10, 10, 170, 130);

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 51, 51));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("PRODUCTOS");
        jPanel3.add(lblTitulo);
        lblTitulo.setBounds(200, 50, 590, 80);

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setOpaque(true);
        jPanel3.add(lblBackground);
        lblBackground.setBounds(0, 0, 800, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLeerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botLeerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botBuscarCodigo;
    public javax.swing.JButton botBuscarDescripcion;
    public javax.swing.JButton botCrear;
    public javax.swing.JButton botEliminar;
    public javax.swing.JButton botLeer;
    public javax.swing.JButton botLimpiar;
    public javax.swing.JButton botMdificar;
    public javax.swing.JButton botSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbProveedor;
    public javax.swing.JTextField jtfCodigo;
    public javax.swing.JTextField jtfCosto;
    public javax.swing.JTextField jtfDescripcion;
    public javax.swing.JTextField jtfPrecio;
    public javax.swing.JTextField jtfStockMax;
    public javax.swing.JTextField jtfStockMin;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    public javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
